spring:
  main:
    banner-mode: off
  mvc:
    view:
      prefix: classpath:templates
      suffix: .html
  thymeleaf:
    prefix: classpath:templates
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: ${spring.jpa.database-platform}
        hbm2ddl:
          auto: ${spring.jpa.hibernate.ddl-auto}
        show_sql: ${spring.jpa.show-sql}
        format_sql: ${spring.jpa.show-sql}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: P@ssw0rd
server:
  port: 8080