spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: P@ssw0rd
server:
  port: 8080